stages:
  - test

test:
  stage: test
  image: golang:latest
  coverage: /^coverage:\s(\d+(?:\.\d+)?%)/
  before_script:
    - apt-get update
    - apt-get install -y busybox-static
    - go install github.com/boumenot/gocover-cobertura@latest
    - go install gotest.tools/gotestsum@latest
  script:
    - gotestsum --format testname --junitfile report.xml -- -coverprofile=coverage.txt -race ./...
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml


golangci-linter:
  stage: test
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  allow_failure: true
  script:
    - golangci-lint run --timeout 1h ./...

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml